// Generated by Grafana k6 Studio (1.10.0) on 2026-01-19T02:30:04.246Z

import { browser } from "k6/browser";

export const options = {
  scenarios: {
    default: {
      executor: "shared-iterations",
      options: { browser: { type: "chromium" } },
    },
  },
};

export default async function () {
  const page = await browser.newPage();

  await page.goto("https://sistema.homologacao.apphealth.com.br/#/");

  await page.getByPlaceholder("CPF", { exact: true }).fill("678.428.630-83 ");

  await page.getByPlaceholder("Senha", { exact: true }).fill("67842");

  await page.getByRole("button", { name: "Entrar", exact: true }).click();

  await page.locator("div:nth-of-type(2) > a").click();

  await page.getByRole("button", { name: "Ir para data de hoje", exact: true }).waitFor();
  
  await page.getByRole("button", { name: "Ir para data de hoje", exact: true }).click();

  await page.locator("div:nth-of-type(7) button:nth-of-type(3)").click();

  await page.locator("#nome").fill("abcd1");

  await page.locator("#telefone").fill("(11) 11111-1111");

  await page
    .locator("div:nth-of-type(1) > div > div:nth-child(2) > input")
    .fill("23:30");

  await page.getByRole("button", { name: "Agendar", exact: true }).click();

  await page
    .locator("div:nth-of-type(2) > div:nth-of-type(2) > .material-icons")
    .click();

  await page.locator(".css-lbibno div:nth-of-type(2)").click();

  await page.locator("div:nth-child(2) > div > p").click();

  await page.locator(".css-lbibno > div > div > div:nth-of-type(1)").click();

  await page.getByRole("button", { name: "Agendar", exact: true }).click();

  await page.locator("div:nth-of-type(8) button:nth-of-type(3)").click();

  await page.locator("#nome").fill("abcd2");

  await page.locator("#telefone").fill("(22) 22222-2222");

  await page
    .locator("div:nth-of-type(1) > div > div:nth-child(2) > input")
    .fill("23:31");

  await page.getByRole("button", { name: "Agendar", exact: true }).click();

  await page.getByRole("button", { name: "Sim", exact: true }).click();
}
